---
layout: default
title:  О блоге
---

* О блоге

Под общую тематику блога подходит фраза, с моей точки зрения, лучше
всего отражающая идею OpenSource:

/--- Что-то не устраивает? Будь мужиком --- прими как есть и сделай
лучше!/

Не по душе готовые шаблоны, /WYSIWYG/-редактор или мышиная возня по
менюшкам в [[http://www.blogger.com][Blogger]]? Найди хостинг, генератор сайтов а-ля [[http://jekyllrb.com][Jekyll]] и
создай блог сам! Очередной /user-friendly/ дистрибутив Linux обзавёлся
искусственным интеллектом, теперь живёт своей жизнью и жутко тормозит?
Освой [[http://www.gentoo.org][Gentoo]] и сделай [[http://en.gentoo-wiki.com/wiki/Custom_Stage4][свой stage4]]! Любимый редактор требует слишком
много телодвижений в повседневной работе? Будь мужиком --- настрой
[[http://www.gnu.org/software/emacs/][Emacs]]!

Духу OpenSource претит отношение к нему как к \laquo{}бесплатному пиву\raquo, о
чём лишний раз напоминает данный блог. Задуман он как сборник рецептов
на память, когда есть желание поделиться ими с другими. Вряд ли вы
найдёте обзоры готовых изделий от ведущих производителей софта, зато
то тут, то там разбросаны маленькие рецепты и заметки на полях.
Которые, надеюсь, пригодятся ещё кому-нибудь, кроме меня. Если есть
желание узнать что-нибудь новое или поделиться им с другими, добро
пожаловать на страницы блога!
