---
layout:   post
title:    Emacs Daemon против долгого старта Emacs
comments: yes
---

Бытует мнение, что *Emacs* --- это \laquo{}тормоз\raquo мира редакторов, из-за долгой загрузки файлов инициализации во время запуска. Что буквально вынуждает часть пользователей постоянно держать *Emacs* открытым. Хотя волшебная таблетка придумана давно: запуск фонового процесса [[http://www.emacswiki.org/emacs/EmacsAsDaemon][Emacs Daemon]] и замена вызова *Emacs* на запуск [[http://www.emacswiki.org/emacs/EmacsClient][Emacs Client]]. Фоновый процесс (демон) берёт на себя инициализацию настроек, тогда как редактор (клиент) просто подключается к нему во время старта, экономя ваше время.

*** Основы работы с Emacs Daemon

*Emacs Daemon* стартует по команде
#+begin_src console
  $ emacs --daemon
#+end_src
инициализирует настройки редактора и затем запускает сервер, который отслеживает подключения клиента. В свою очередь, *Emacs Client* открывает сессию *Emacs* либо в консоли:
#+begin_src console
  $ emacsclient -t
#+end_src
либо в новом фрейме:
#+begin_src console
  $ emacsclient -c
#+end_src
Однако, если демон не был запущен, то подключения не произойдёт; чтобы исключить подобный казус, задействуем опцию =-a=:
#+begin_src console
  $ emacsclient -c -a ""
#+end_src
Тогда *Emacs Client* произведёт запуск демона самостоятельно, если этого не было сделано до него. Выход из *Emacs* с завершением работы клиента осуществляется по хоткею =C-x #=.

*Emacs Daemon* хранит состояние буферов между подключениями клиента, остановить его можно командой =M-x kill-emacs= или =M-x save-buffers-kill-emacs=, последняя позволяет сохранить буферы редактора перед завершением. За пределами *Emacs* можно не только запускать *Emacs Client*, но и передавать ему на исполнение [[http://ru.wikipedia.org/wiki/Emacs_Lisp][Elisp]]-выражения. Например, выполнить остановку демона:
#+begin_src console
  $ emacsclient -e "(kill-emacs)"
#+end_src

Ложка дёгтя заключается в использовании сборки *Emacs* с *Gtk*: [[https://bugzilla.gnome.org/show_bug.cgi?id=85715][давний баг]] приводит к краху *Emacs Daemon* после закрытия окна редактора. Сборка на основе *Lucid Toolkit* избавлена от этого бага (гентушники, лениво потягиваясь, ставят =USE=​"Xaw3d -gtk -gtk3"​=).

*** Запуск и остановка Emacs Daemon

Разумно это возложить на систему инициализации *Linux* или совместить с запуском [[http://ru.wikipedia.org/wiki/X_Window_System][X Window System]]. Второй вариант предполагает внесение команд запуска и остановки *Emacs Daemon* в файлы =~/.bash_profile= и =~/.bash_logout=, соответственно.

Ниже в этом параграфе речь пойдёт о *Gentoo* и пакете =emacs-daemon=, чьё назначение, очевидно, следует из названия. Каждому пользователю =username= для подключения к *Emacs Daemon* необходимо иметь свой экземпляр демона, который запускался бы с привилегиями пользователя. Создайте символьную ссылку в директории =/etc/init.d/= (/но не копируйте сам скрипт, что лишит вас важных обновлений/):
#+begin_src console
  # cd /etc/init.d/
  # ln -s emacs emacs.username
#+end_src
и скрипт запуска автоматически определит пользователя по =username=. Теперь запустим демона
#+begin_src console
  # /etc/init.d/emacs.username start
#+end_src
а также добавим в загрузку
#+begin_src console
  # rc-update add emacs.username default
#+end_src

Настраивается демон с помощью файла =/etc/conf.d/emacs=. Скрипты, указанные в переменных =EMACS_START= и =EMACS_STOP=, запускаются на соответствующих стадиях. Для корректного завершения *Emacs Daemon* /настоятельно рекомендую указать следующий скрипт для остановки/:
#+begin_src sh
  EMACS_STOP="/usr/libexec/emacs/emacs-stop.sh"
#+end_src
который идёт вместе с пакетом =emacs-daemon=. Для подробного вывода сообщений при инициализации просто установите переменную
#+begin_src sh
  EMACS_DEBUG="y"
#+end_src

*** Подводные камни Emacs Daemon

При использовании не консольного шрифта к ошибке ведёт [[http://www.emacswiki.org/emacs/SetFonts][стандартная установка шрифта]] в файле инициализации
#+begin_src emacs-lisp
  (set-face-attribute 'default nil :font FONT)
#+end_src
где =FONT= --- имя шрифта в виде строки, например, =​"Droid Sans Mono 10"​=. Зато подойдёт другой способ:
#+begin_src emacs-lisp
  (add-to-list 'default-frame-alist '(font . FONT))
#+end_src

Также во время запуска демона исключите вопросы от *Emacs*, так как возможности дать ответ у вас не будет, и на первом же вопросе загрузка прекратится. Например, если сохранение сессий *Emacs* возложено на плечи [[http://www.emacswiki.org/emacs/DeskTop][DeskTop]], то следует заранее определиться с его поведением на случай конфликта между используемой и сохранённой сессиями. Для безусловного сохранения сессий задайте переменной =desktop-save= значение =t= вместо =ask-if-new=, используемого по умолчанию. За загрузку конфликтующей сессии отвечает переменная =desktop-load-locked-desktop=: значение =t= разрешает работу с сессией другого *Emacs Daemon*, тогда как =nil=, наоборот, запрещает. Использовать =nil= имеет смысл тогда, когда в системе есть несколько пользователей, имеющих доступ к одним и тем же сессиям *DeskTop*. В остальном, смело можно использовать значение =t=.
